// NOTE: These ABIs are from the STA/Soneta project and may be updated later.
// STA token references in these ABIs correspond to NTA in our UI.
// this file was generated by scripts/update-liquity-abis.ts
// please do not edit it manually
export const OneVaultAdapterV2 = [{
  "inputs": [
    {
      "internalType": "address",
      "name": "one_",
      "type": "address"
    }
  ],
  "stateMutability": "nonpayable",
  "type": "constructor"
},
{
  "inputs": [
    {
      "internalType": "uint256",
      "name": "requested",
      "type": "uint256"
    },
    {
      "internalType": "uint256",
      "name": "available",
      "type": "uint256"
    }
  ],
  "name": "InsufficientShares",
  "type": "error"
},
{
  "inputs": [
    {
      "internalType": "uint40",
      "name": "fromTs",
      "type": "uint40"
    },
    {
      "internalType": "uint40",
      "name": "toTs",
      "type": "uint40"
    }
  ],
  "name": "InvalidWindow",
  "type": "error"
},
{
  "inputs": [],
  "name": "ReentrancyGuardReentrantCall",
  "type": "error"
},
{
  "inputs": [
    {
      "internalType": "address",
      "name": "token",
      "type": "address"
    }
  ],
  "name": "SafeERC20FailedOperation",
  "type": "error"
},
{
  "inputs": [
    {
      "internalType": "uint40",
      "name": "queryTs",
      "type": "uint40"
    },
    {
      "internalType": "uint40",
      "name": "currentTs",
      "type": "uint40"
    }
  ],
  "name": "TimestampInFuture",
  "type": "error"
},
{
  "inputs": [],
  "name": "ZeroAddress",
  "type": "error"
},
{
  "inputs": [],
  "name": "ZeroAmount",
  "type": "error"
},
{
  "anonymous": false,
  "inputs": [
    {
      "indexed": true,
      "internalType": "address",
      "name": "caller",
      "type": "address"
    },
    {
      "indexed": true,
      "internalType": "address",
      "name": "receiver",
      "type": "address"
    },
    {
      "indexed": false,
      "internalType": "uint256",
      "name": "assets",
      "type": "uint256"
    },
    {
      "indexed": false,
      "internalType": "uint256",
      "name": "shares",
      "type": "uint256"
    }
  ],
  "name": "Deposited",
  "type": "event"
},
{
  "anonymous": false,
  "inputs": [
    {
      "indexed": true,
      "internalType": "address",
      "name": "caller",
      "type": "address"
    },
    {
      "indexed": true,
      "internalType": "address",
      "name": "receiver",
      "type": "address"
    },
    {
      "indexed": false,
      "internalType": "uint256",
      "name": "assets",
      "type": "uint256"
    },
    {
      "indexed": false,
      "internalType": "uint256",
      "name": "shares",
      "type": "uint256"
    }
  ],
  "name": "Withdrawn",
  "type": "event"
},
{
  "inputs": [
    {
      "internalType": "address",
      "name": "user",
      "type": "address"
    },
    {
      "internalType": "uint40",
      "name": "fromTs",
      "type": "uint40"
    },
    {
      "internalType": "uint40",
      "name": "toTs",
      "type": "uint40"
    }
  ],
  "name": "averageUnitsOf",
  "outputs": [
    {
      "internalType": "uint256",
      "name": "units",
      "type": "uint256"
    }
  ],
  "stateMutability": "view",
  "type": "function"
},
{
  "inputs": [
    {
      "internalType": "address",
      "name": "user",
      "type": "address"
    }
  ],
  "name": "currentRawUnitsOf",
  "outputs": [
    {
      "internalType": "uint256",
      "name": "units",
      "type": "uint256"
    }
  ],
  "stateMutability": "view",
  "type": "function"
},
{
  "inputs": [],
  "name": "currentTotalRawUnits",
  "outputs": [
    {
      "internalType": "uint256",
      "name": "units",
      "type": "uint256"
    }
  ],
  "stateMutability": "view",
  "type": "function"
},
{
  "inputs": [],
  "name": "currentUnitScaleX18",
  "outputs": [
    {
      "internalType": "uint256",
      "name": "scaleX18",
      "type": "uint256"
    }
  ],
  "stateMutability": "pure",
  "type": "function"
},
{
  "inputs": [
    {
      "internalType": "uint256",
      "name": "amount",
      "type": "uint256"
    },
    {
      "internalType": "address",
      "name": "receiver",
      "type": "address"
    }
  ],
  "name": "deposit",
  "outputs": [
    {
      "internalType": "uint256",
      "name": "sharesOut",
      "type": "uint256"
    }
  ],
  "stateMutability": "nonpayable",
  "type": "function"
},
{
  "inputs": [
    {
      "internalType": "uint256",
      "name": "index",
      "type": "uint256"
    }
  ],
  "name": "getGlobalCheckpoint",
  "outputs": [
    {
      "components": [
        {
          "internalType": "uint40",
          "name": "ts",
          "type": "uint40"
        },
        {
          "internalType": "uint256",
          "name": "cumulativeUnitSeconds",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "unitsAfter",
          "type": "uint256"
        }
      ],
      "internalType": "struct TwabAdapterBase.Checkpoint",
      "name": "cp",
      "type": "tuple"
    }
  ],
  "stateMutability": "view",
  "type": "function"
},
{
  "inputs": [
    {
      "internalType": "address",
      "name": "user",
      "type": "address"
    },
    {
      "internalType": "uint256",
      "name": "index",
      "type": "uint256"
    }
  ],
  "name": "getUserCheckpoint",
  "outputs": [
    {
      "components": [
        {
          "internalType": "uint40",
          "name": "ts",
          "type": "uint40"
        },
        {
          "internalType": "uint256",
          "name": "cumulativeUnitSeconds",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "unitsAfter",
          "type": "uint256"
        }
      ],
      "internalType": "struct TwabAdapterBase.Checkpoint",
      "name": "cp",
      "type": "tuple"
    }
  ],
  "stateMutability": "view",
  "type": "function"
},
{
  "inputs": [],
  "name": "globalCheckpointCount",
  "outputs": [
    {
      "internalType": "uint256",
      "name": "count",
      "type": "uint256"
    }
  ],
  "stateMutability": "view",
  "type": "function"
},
{
  "inputs": [],
  "name": "one",
  "outputs": [
    {
      "internalType": "contract IERC20",
      "name": "",
      "type": "address"
    }
  ],
  "stateMutability": "view",
  "type": "function"
},
{
  "inputs": [
    {
      "internalType": "address",
      "name": "user",
      "type": "address"
    }
  ],
  "name": "rawUnitsOf",
  "outputs": [
    {
      "internalType": "uint256",
      "name": "units",
      "type": "uint256"
    }
  ],
  "stateMutability": "view",
  "type": "function"
},
{
  "inputs": [
    {
      "internalType": "address",
      "name": "user",
      "type": "address"
    }
  ],
  "name": "sharesOf",
  "outputs": [
    {
      "internalType": "uint256",
      "name": "shares",
      "type": "uint256"
    }
  ],
  "stateMutability": "view",
  "type": "function"
},
{
  "inputs": [],
  "name": "sync",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
},
{
  "inputs": [
    {
      "internalType": "uint40",
      "name": "fromTs",
      "type": "uint40"
    },
    {
      "internalType": "uint40",
      "name": "toTs",
      "type": "uint40"
    }
  ],
  "name": "totalAverageUnits",
  "outputs": [
    {
      "internalType": "uint256",
      "name": "units",
      "type": "uint256"
    }
  ],
  "stateMutability": "view",
  "type": "function"
},
{
  "inputs": [],
  "name": "totalRawUnits",
  "outputs": [
    {
      "internalType": "uint256",
      "name": "units",
      "type": "uint256"
    }
  ],
  "stateMutability": "view",
  "type": "function"
},
{
  "inputs": [],
  "name": "totalShares",
  "outputs": [
    {
      "internalType": "uint256",
      "name": "shares",
      "type": "uint256"
    }
  ],
  "stateMutability": "view",
  "type": "function"
},
{
  "inputs": [
    {
      "internalType": "address",
      "name": "user",
      "type": "address"
    }
  ],
  "name": "userCheckpointCount",
  "outputs": [
    {
      "internalType": "uint256",
      "name": "count",
      "type": "uint256"
    }
  ],
  "stateMutability": "view",
  "type": "function"
},
{
  "inputs": [
    {
      "internalType": "uint256",
      "name": "shareAmount",
      "type": "uint256"
    },
    {
      "internalType": "address",
      "name": "receiver",
      "type": "address"
    }
  ],
  "name": "withdraw",
  "outputs": [
    {
      "internalType": "uint256",
      "name": "assetsOut",
      "type": "uint256"
    }
  ],
  "stateMutability": "nonpayable",
  "type": "function"
}] as const;
