// NOTE: These ABIs are from the STA/Soneta project and may be updated later.
// STA token references in these ABIs correspond to NTA in our UI.
// this file was generated by scripts/update-liquity-abis.ts
// please do not edit it manually
export const TwabAdapterBase =
  [{
    "inputs": [
      {
        "internalType": "uint40",
        "name": "fromTs",
        "type": "uint40"
      },
      {
        "internalType": "uint40",
        "name": "toTs",
        "type": "uint40"
      }
    ],
    "name": "InvalidWindow",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint40",
        "name": "queryTs",
        "type": "uint40"
      },
      {
        "internalType": "uint40",
        "name": "currentTs",
        "type": "uint40"
      }
    ],
    "name": "TimestampInFuture",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "internalType": "uint40",
        "name": "fromTs",
        "type": "uint40"
      },
      {
        "internalType": "uint40",
        "name": "toTs",
        "type": "uint40"
      }
    ],
    "name": "averageUnitsOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "units",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      }
    ],
    "name": "currentRawUnitsOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "units",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "currentTotalRawUnits",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "units",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "currentUnitScaleX18",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "scaleX18",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      }
    ],
    "name": "getGlobalCheckpoint",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint40",
            "name": "ts",
            "type": "uint40"
          },
          {
            "internalType": "uint256",
            "name": "cumulativeUnitSeconds",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "unitsAfter",
            "type": "uint256"
          }
        ],
        "internalType": "struct TwabAdapterBase.Checkpoint",
        "name": "cp",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      }
    ],
    "name": "getUserCheckpoint",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint40",
            "name": "ts",
            "type": "uint40"
          },
          {
            "internalType": "uint256",
            "name": "cumulativeUnitSeconds",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "unitsAfter",
            "type": "uint256"
          }
        ],
        "internalType": "struct TwabAdapterBase.Checkpoint",
        "name": "cp",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "globalCheckpointCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "count",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      }
    ],
    "name": "rawUnitsOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "units",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "sync",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint40",
        "name": "fromTs",
        "type": "uint40"
      },
      {
        "internalType": "uint40",
        "name": "toTs",
        "type": "uint40"
      }
    ],
    "name": "totalAverageUnits",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "units",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "totalRawUnits",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "units",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      }
    ],
    "name": "userCheckpointCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "count",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }] as const;
